sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt install p7zip-full
    - wget https://github.com/c4pr1c3/LinuxSysAdmin/blob/master/exp/chap0x04/web_log.tsv.7z
    - 7z x web_log.tsv.7z

script:
  - bash task2.sh
  - bash task3.sh -i
  - bash task3.sh -h
  - bash task3.sh -c
  - bash task3.sh -u
  - bash task3.sh -r
  - shellcheck task1.sh
  - shellcheck task2.sh
  - shellcheck task3.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
